# Generated by Django 4.0.6 on 2022-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='horarios',
            field=models.CharField(max_length=50),
        ),
    ]
