# Generated by Django 4.0.6 on 2022-09-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auten', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
